name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:

      - name: Perform checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system --dev
          pip install pywin32-ctypes pefile
          pip freeze

      - name: Perform build
        run: pyinstaller --onefile -y --distpath . src/anakin.py

      - name: Upload artifact - Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: anakin.exe
          path: anakin.exe

      - name: Upload artifact - Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: anakin
          path: anakin
